"""Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms."""

N1 = 1
N2 = 2
N3 = 0
N_MAX = 4000000
SUM_N = N1 + N2

while True:
    N3 = N1 + N2
    if N3 >= N_MAX:
        break
    N1, N2 = N2, N3

    if N3 % 2 == 0:
        SUM_N += N3
        # print(SUM_N, N3)

print(f"Summ = {SUM_N}")
